### ISSUE TITLE
Save and Close button causing an error

### ISSUE THREAD

**Issue by catharsisjelly** [lekoala/silverstripe-cms-actions#36] opened 2023-06-21 12:28 UTC
Thanks for this module. installed it today and after a `flush=1` I click the "Save and Close" button and am faced with this error

```
Action 'admin' isn't available on class SilverStripe\Versioned\VersionedGridFieldItemRequest.
```

The error was caused by a `GET` to `https://localhost:4430/admin/convention/App-Model-Exhibitor/EditForm/field/App-Model-Exhibitor/item/1/admin/convention/App-Model-Exhibitor`

My model is in the namespace `App\Model` and is called `Exhibitor`. I don't use `Vesioned` directly, I think this has been pulled in by your module somehow. Happy to help and happy to provide more details where I can.

* Siverstripe v5

**Comment by lekoala** [comment] 2023-06-21 16:09
i did a quick test on a ss5 install, and my model admin is working fine at first glance

from your url, i think something is odd
admin/convention/App-Model-Exhibitor/EditForm/field/App-Model-Exhibitor/item/1/admin/convention/App-Model-Exhibitor

why is there an  admin/convention after /item/1 ?

the url on my end looks like this
/admin/my_admin/My-Namespace-DemoNsObject/EditForm/field/My-Namespace-DemoNsObject/item/1/edit
/admin/my_admin/My-Namespace-DemoNsObject/EditForm/field/My-Namespace-DemoNsObject/item/1/ItemEditForm
/admin/my_admin/My-Namespace-DemoNsObject

**Comment by catharsisjelly** [comment] 2023-06-21 16:14
That is my `ModelAdmin` class I have multiple objects being handled in this one place for ease of access.

**Comment by lekoala** [comment] 2023-06-22 07:59
Tried again with a similar model admin as yours, it works fine
Can you try to replicate this on a fresh install?

Another option is to look what happens when you do save and close

https://github.com/lekoala/silverstripe-cms-actions/blob/a220f889786368d5d11659b2e0304fd269f0191f/src/ActionsGridFieldItemRequest.php#L666

It should be very straightforward. Can you dump the value of $link and see what you got there?

your model admin name shouldn't be there twice in the url
**admin/convention/App-Model-Exhibitor**/EditForm/field/App-Model-Exhibitor/item/1/**admin/convention/App-Model-Exhibitor**

**Comment by w-huber** [comment] 2023-06-22 09:56
I was beginning to think I was the only one running into this error. In my local installation (Docker with Silverstripe 4.13) everything works fine, if I transfer the data to my web hoster (in this case Ionos or Strato) I get exactly this error.
I tried a lot and found this place in the code that causes the problem.

Removing line 672 solves the problem for ModelAdmin classes.

https://github.com/lekoala/silverstripe-cms-actions/blob/a220f889786368d5d11659b2e0304fd269f0191f/src/ActionsGridFieldItemRequest.php#L671-L674



The redirect() function from ModelAdmin executes the following code:
https://github.com/silverstripe/silverstripe-admin/blob/971046c5219afcb295bead52830395cc3fe02337/code/LeftAndMain.php#L836-L859
```
    public function redirect(string $url, int $code = 302): HTTPResponse
    {
        if ($this->getRequest()->isAjax()) {
            $response = $this->getResponse();
            $response->addHeader('X-ControllerURL', $url);
            if ($this->getRequest()->getHeader('X-Pjax') && !$response->getHeader('X-Pjax')) {
                $response->addHeader('X-Pjax', $this->getRequest()->getHeader('X-Pjax'));
            }
            $newResponse = new LeftAndMain_HTTPResponse(
                $response->getBody(),
                $response->getStatusCode(),
                $response->getStatusDescription()
            );
            foreach ($response->getHeaders() as $k => $v) {
                $newResponse->addHeader($k, $v);
            }
            $newResponse->setIsFinished(true);
            $this->setResponse($newResponse);
            // Actual response will be re-requested by client
            return $newResponse;
        } else {
            return parent::redirect($url, $code);
        }
    }
```


The redirect() function from Controller executes the following code:
https://github.com/silverstripe/silverstripe-framework/blob/0c40cc9b3d9658ad868c560059c88255d2ee0674/src/Control/Controller.php#L600-L611
```
    public function redirect(string $url, int $code = 302): HTTPResponse
    {
        $response = $this->getResponse();
        if ($response->getHeader('Location') && $response->getHeader('Location') != $url) {
            user_error("Already directed to " . $this->getResponse()->getHeader('Location')
                . "; now trying to direct to $url", E_USER_WARNING);
            return $response;
        }
        $response = parent::redirect($url, $code);
        $this->setResponse($response);
        return $response;
    }
```

**Comment by lekoala** [comment] 2023-06-22 10:15
@w-huber @catharsisjelly can you try with these changes
https://github.com/lekoala/silverstripe-cms-actions/commit/5e7c5f87e945a084b7c55fc5455300ec75c34186

i was not really happy anyway with this hack, and i'm not even sure anymore why i did it :-) never had any issue before, but if it fixes your issue, happy to remove it

**Comment by w-huber** [comment] 2023-06-22 11:23
As I mentioned above, then it works. Maybe you could check in advance for the ModelAdmin class.

```
        // Prevent Already directed to errors
        if (!$controller instanceof ModelAdmin) {
            $controller->getResponse()->addHeader("Location", $link);
        }
```

**Comment by lekoala** [comment] 2023-06-22 11:32
i will investigate more later, in the meantime it seems its better to remove it for now
https://github.com/lekoala/silverstripe-cms-actions/releases/tag/1.4.1

i need to check why i did that in the first place :-)

**Comment by catharsisjelly** [comment] 2023-06-22 11:32
@lekoala That patch fixed the problem thanks for the patch

**Comment by lekoala** [comment] 2023-06-22 11:36
ok great, closing the issue and will keep that in mind to avoid any regression in the future

**Closed by lekoala** 2023-06-22 11:36 UTC
