### ISSUE TITLE
CMSAction - Removes Gridfield details on saving

### ISSUE THREAD

**Issue by mspacemedia** [lekoala/silverstripe-cms-actions#19] opened 2022-04-24 13:13 UTC
This might be my implementation, but when I click an item in a gridfield and then the resultant CMSAction on that object the module removes the Gridfield status from the URL, this then means clicking `next/prev` or` save and next` do not work as normal.

`->setShouldRefresh` to `true` or `false` makes no difference either.

My code is in updateCMSActions on an extension:

`$getLogo = CustomAction::create('doGetLogo', 'Get Logo');`
`$getLogo->setShouldRefresh(false);`
`$actions->push($getLogo);`

**Comment by lekoala** [comment] 2022-04-24 16:22
It might depend on what your action does ? I'm not an expert on gridfield state so maybe it's a matter of checking when the URL is updated incorrectly. I don't see how an Ajax request to an action should change anything

**Comment by mspacemedia** [comment] 2022-04-24 16:26
Me either @lekoala, all the action does it guzzle a logo from a URL and save a local copy. It then writes the dataobject to the database to store the ID of the newly 'minted' image in the Filesystem. I then tried with `setShouldRefresh` set to true and false and both have the same effect on the URL it strips out the `GridField` URL data…

I shall dig a bit deeper in XDebug

**Comment by mspacemedia** [comment] 2022-04-24 16:53
`https://github.com/isobar-nz/silverstripe-persistentgridfield` appears to fix the issue - to a degree…

**Comment by lekoala** [comment] 2022-05-18 10:47
@mspacemedia actually just tried to test this, and i never have gridfield status in the url so prev/next (even the built in nav from silverstripe) always apply to the unfiltered list.
which version of silverstripe are you using?
this seems actually an issue for a while and not really specific to this module i believe
https://github.com/silverstripe/silverstripe-framework/issues/3229

**Comment by mspacemedia** [comment] 2022-05-18 10:50
@lekoala I'm seeing this issue in the latest SS4 build from this in composer:

        "silverstripe/recipe-plugin": "^1.2",
        "silverstripe/recipe-cms": "~4.9.0@stable"

**Comment by lekoala** [comment] 2022-06-17 15:18
I'm keeping this open but I don't plan to work on it until I have a reproduceable example. If anyone has the issue or finds a solution, a PR is welcome

**Comment by silverstripesk** [comment] 2023-03-28 12:15
From SilverStripe 4.12 gridfield state is present in URL. Saving DataObject removes gridState from URL. Default SilverStripe implementation does not remove this from URL. Also Prev/Next buttons do not respect filter applied on gridfield (is present in URL on selected DataObject).

**Comment by lekoala** [comment] 2023-03-28 14:27
@silverstripesk wow not sure how i missed that :)
fix is in progress, this is what i've made so far which work for save and close, save and prev/next
https://github.com/lekoala/silverstripe-cms-actions/commit/bfe61f94186ae9d59ef0efd3fb933656620eb651

**Comment by lekoala** [comment] 2023-03-29 10:03
@silverstripesk @mspacemedia i've made quite a few grid state related updates on master, if you can give it a try and let me know how it goes ? ;-)
it might not be 100% perfect, but i do see a lot of improvements on my test project

**Comment by silverstripesk** [comment] 2023-05-10 13:00
works on Prev/Next/Save+Close
doesn't work on Save+Prev/Save+Next

**Comment by lekoala** [comment] 2023-05-10 13:41
@silverstripesk that's very odd, it seems to be working just fine for me (tested in modeladmin, on base grid and nested grids)
i've released a new version https://github.com/lekoala/silverstripe-cms-actions/releases/tag/1.3.13 can you make sure to test with it ?

**Comment by silverstripesk** [comment] 2023-05-10 13:56
great, now work all buttons.

One visual issue: prev/next buttons are missing arrows
![obrázok](https://github.com/lekoala/silverstripe-cms-actions/assets/644242/71abdd1a-6e18-4622-92c2-b5237dac6827)

**Comment by lekoala** [comment] 2023-05-10 14:41
indeed, missed that one ;-)
i'm closing the issue, the css is fixed here
https://github.com/lekoala/silverstripe-cms-actions/releases/tag/1.3.14

**Closed by lekoala** 2023-05-10 14:41 UTC
